version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    container_name: api-solid-pg
    environment:
      POSTGRES_USERNAME: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid
    ports:
      - 5432:5432
